In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# **Numpy Arrays**

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4]   # Define a list
my_array = np.array(my_list)   # Pass the list to np.array()
type(my_array)     # Check the object's type

numpy.ndarray

In [4]:
second_list = [5,6,7,8]
two_d_array = np.array([my_list, second_list])
print(two_d_array)
type(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [5]:
two_d_array.shape

(2, 4)

In [6]:
two_d_array.size

8

In [7]:
two_d_array.dtype

dtype('int64')

In [8]:
# np.identity() to create a square 2d array with 1's across the diagonal
np.identity(n=5)   # Size of the array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
# np.eye() to create a 2d array with 1's across a specified diagonal

np.eye(N = 3, # Number of rows
      M = 5, # Number of columns
      k = 1) # Index of the diagonal (main diagonal (0) is default)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [10]:
# np.ones() to create an array filled with ones:
np.ones(shape = [2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# np.zeros() to create an array filled with zeros :
np.zeros(shape = [4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# **Array Indexing and Slicing**

In [12]:
one_d_array = np.array([1,2,3,4,5,6])
one_d_array[3]   # Get the item at index 3

4

In [13]:
one_d_array[3:]  

array([4, 5, 6])

In [14]:
one_d_array[:: -1]

array([6, 5, 4, 3, 2, 1])

In [15]:
two_d_array = np.array([one_d_array, one_d_array + 6, one_d_array + 12])
print(two_d_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [16]:
# Get the lement at row index 1, column index 4
two_d_array[1,4]

11

In [17]:
# Slice emements starting at row 2, and column 5
two_d_array[1:, 4:]

array([[11, 12],
       [17, 18]])

In [18]:
# reverse both dimensions (180 degree rotation)
two_d_array[::-1, ::-1]

array([[18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])